// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCycm-GPfhXK6a3bNBiJQCyebFUx3QgoEg',
    appId: '1:307691944015:web:1603f0f77c2f96c079923a',
    messagingSenderId: '307691944015',
    projectId: 'tdsip-c4128',
    authDomain: 'tdsip-c4128.firebaseapp.com',
    storageBucket: 'tdsip-c4128.firebasestorage.app',
    measurementId: 'G-5W69GP0WNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAod9QS0yxKa5XLSYPzCQRgjJQN87_3lHM',
    appId: '1:307691944015:android:a06bc2716eb3a90679923a',
    messagingSenderId: '307691944015',
    projectId: 'tdsip-c4128',
    storageBucket: 'tdsip-c4128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUTiLHuREyayYz9yse3yZ992h6NGcH4iU',
    appId: '1:307691944015:ios:b571f182123f0b3179923a',
    messagingSenderId: '307691944015',
    projectId: 'tdsip-c4128',
    storageBucket: 'tdsip-c4128.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUTiLHuREyayYz9yse3yZ992h6NGcH4iU',
    appId: '1:307691944015:ios:b571f182123f0b3179923a',
    messagingSenderId: '307691944015',
    projectId: 'tdsip-c4128',
    storageBucket: 'tdsip-c4128.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCycm-GPfhXK6a3bNBiJQCyebFUx3QgoEg',
    appId: '1:307691944015:web:3a0b634dbd52630679923a',
    messagingSenderId: '307691944015',
    projectId: 'tdsip-c4128',
    authDomain: 'tdsip-c4128.firebaseapp.com',
    storageBucket: 'tdsip-c4128.firebasestorage.app',
    measurementId: 'G-KM4MCRC4WG',
  );
}
